# Generated by Django 3.1.3 on 2020-12-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201201_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='avail',
            field=models.BooleanField(default=True),
        ),
    ]
