# Generated by Django 3.1.3 on 2020-12-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201207_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='avail',
            field=models.SmallIntegerField(default=1),
        ),
    ]
